# Домашнее задание №1 (HW01)

In [8]:
# 1) Импорт библиотеки NumPy
import numpy as np

In [9]:
# 2.1) Создание массивов из обычных списков
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print('arr1 =', arr1)
print('arr2 =\n', arr2)

arr1 = [1 2 3 4]
arr2 =
 [[1 2 3]
 [4 5 6]]


In [10]:
# 2.2) Создание массивов
z = np.zeros((2, 3))     # матрица 2x3 заполненная нулями
o = np.ones(4)           # вектор из четырёх единиц
r = np.arange(0, 10, 2)  # последовательность: 0,2,4,6,8

print('zeros\n', z)
print('ones\n', o)
print('arange\n', r)

zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
ones
 [1. 1. 1. 1.]
arange
 [0 2 4 6 8]


In [11]:
# 3) Атрибуты массива
print('arr2:')
print(arr2)
print('Форма arr2 (shape):', arr2.shape)       # количество строк и столбцов
print('Тип данных arr2 (dtype):', arr2.dtype)  # тип данных

arr2:
[[1 2 3]
 [4 5 6]]
Форма arr2 (shape): (2, 3)
Тип данных arr2 (dtype): int32


In [12]:
# 4) Индексирование и срезы
elem = arr2[1, 2]  # индексация с нуля: строка 1 (вторая), столбец 2 (третья)
print('Отдельный элемент arr2[1,2]:', elem)

# Извлечение подмассива с помощью среза
sub = arr2[0:2, 1:3]  # строки 0..1 и столбцы 1..2
print('Подмассив arr2[0:2, 1:3]:\n', sub)

# Пример с одномерным массивом: взять элементы от 1 до конца (срез)
print('arr1[1:]:', arr1[1:])

Отдельный элемент arr2[1,2]: 6
Подмассив arr2[0:2, 1:3]:
 [[2 3]
 [5 6]]
arr1[1:]: [2 3 4]


In [13]:
# 5.1) Векторные операции
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Поэлементное сложение и умножение
sum_xy = x + y
prod_xy = x * y

print('x =', x)
print('y =', y)
print('x + y =', sum_xy)
print('x * y =', prod_xy)

# Прибавление скаляра к вектору (каждый элемент увеличится на 10)
print('x + 10 =', x + 10)

x = [1 2 3]
y = [4 5 6]
x + y = [5 7 9]
x * y = [ 4 10 18]
x + 10 = [11 12 13]


In [14]:
# 5.2) Простая статистика
print('mean(x) =', np.mean(x))
print('sum(y) =', np.sum(y))
print('min(arr2) =', np.min(arr2))
print('max(arr2) =', np.max(arr2))
print('std(arr2) =', np.std(arr2))  # стандартное отклонение

mean(x) = 2.0
sum(y) = 15
min(arr2) = 1
max(arr2) = 6
std(arr2) = 1.707825127659933
